# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        enabled: true
        mailer: App\Security\TwoFactor\EmailAuthCodeMailer
        sender_email: toto@yahoo.fr
        sender_name: Toto
        digits: 6
        template: security/2fa_form.html.twig